INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (1, '赵一');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (2, 'opp');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (3, 'ppo');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (4, 'jasper');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (5, 'yuyu');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (6, 'fuil');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (7, 'olp');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (8, 'ann');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (9, 'karl');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (10, 'steel');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (11, 'hutool');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (12, 'lam');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (13, 'soo');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (14, 'lklk');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (15, 'qwp');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (16, 'lok');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (17, 'spring');
INSERT INTO tb_user (USER_ID, USER_NAME)
VALUES (18, 'lpo');