my:
  config:
    age: 20
    enable: true
    name: karl
server:
  port: 8090
spring:
  profiles:
    active: test
#  datasource:
#    password: sa
#    url: jdbc:h2:mem:dbtest
#    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  main:
#    banner-mode: off
#  sql:
#    init:
#      data-locations: classpath:db/data.sql
#      platform: h2
#      schema-locations: classpath:db/schema.sql