spring:
  datasource:
    url: jdbc:mysql://47.57.68.189:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  main:
    banner-mode: off
server:
  port: 8085
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  global-config:
    banner: off